### PR TITLE
Add Wizipsum

### PR DESCRIPTION
**Pull request by Zhouzi**
Wizipsum lets you add your own content so you can use and share it through the demo page and Chrome Extension. It's also a little JavaScript library available as an npm package.

* [GitHub Repository](https://github.com/wizbii/wizipsum)
* [npm package](https://www.npmjs.com/package/wizipsum)
* [Demo Page](http://wizbii.github.io/wizipsum)
* [Chrome Extension](https://chrome.google.com/webstore/detail/wizipsum/ncibdpfgnoldfhagojkniefnaokacfhf)

### CODE REVIEW

**Comment by Zhouzi** [comment]
Oh and I wasn't sure about the category so let me know if I should move it elsewhere ;)

**Comment by templeman** [comment]
This is interesting. Ultimately I think this belongs in a section for "Tools" or something like that, but let's leave it where it is for the moment. Could you please squash your commits down to just one?

**Comment by Zhouzi** [comment]
Sure, here it is :)

**Comment by templeman** [comment]
Great! Thank you for the contribution.

**Pull request merged**
