### PR TITLE
add HTML section

### PR DESCRIPTION
**Pull request by waldyrious**

### CODE REVIEW

**Comment by waldyrious** [comment]
@templeman ping :)

**Comment by waldyrious** [comment]
@templeman friendly reminder, hoping to catch you around!

**Comment by waldyrious** [comment]
Any news, @templeman?

**Comment by templeman** [comment]
Hi @waldyrious. Thanks for the pull request 😄 
It makes sense to point out which generators support HTML output, but I think it's better to identify such entries with a simple `HTML` tag, rather than create a new category. That way entries from all different categories can be included. Since you submitted this request I've changed the way entries are tagged to hopefully be more useful and searchable.

RoughDraft.js is unique and I think it best belongs under "Tools, Apps, and Extensions".

If you'd care to update your PR then I would gladly merge.

**Comment by waldyrious** [comment]
Just to be sure, does updating the PR mean:
- adding RoughDraft.js to the "Tools, Apps, and Extensions" section, with the HTML tag
- adding HTML5-ipsum next to the HTML-ipsum entry, with a HTML tag
- anything else?

**Comment by templeman** [comment]
That should do it.

**Comment by waldyrious** [comment]
I'm loving github's new features. Conflict resolution in the browser ftw!

**Pull request merged**
